const {Router} = require('express')
const { getUsers } = require('../controllers/auth')
const { registerValidation, loginValidation, updateValidation } = require('../vaildators/auth')
const { validationMiddleware } = require('../middlewares/validations-middleware')
const { register } = require('../controllers/register')
const { login } = require('../controllers/login')
const { protected } = require('../controllers/protected')
const { userAuth } = require('../middlewares/auth-middleware')
const { logout } = require('../controllers/logout')
const { updateFirstname, updateLastname, 
    updateEmail, updateAccountInfo, changePassword, 
    updateActivity, updateProfile, updateSubAccCode, updateTotal } = require('../controllers/update')
const { getRefLink, getRefId, getReferrals, getReferralsSize, getTopReferrals } = require('../controllers/referral')
const { getRef, createSub, getHistory } = require('../controllers/paystack')
const { createSponPost, getAllPosts, getPostById } = require('../controllers/sponosredpost')
const { createComment, getCommentForPost } = require('../controllers/comments')
const { getUser } = require('../controllers/getUser')
const { validateData } = require('../controllers/validateRegInfo')
// const { sendImgToCloud } = require('../controllers/cloudinary')
const router = Router()

router.get('/get-users', getUsers) 
router.get('/getuser/:user_id', getUser)
router.get('/protected', protected)
router.post('/validate-registration', registerValidation, validateData)
router.post('/register', register)
router.post('/login', loginValidation, validationMiddleware, login)
router.post('/createsubaccount', createSub) 
router.post('/createapost', createSponPost) 
router.post('/posts/:postId/comments', createComment) 
router.get('/getallposts', getAllPosts) 
router.get('/posts/:postId/comments', getCommentForPost) 
router.get('/logout', logout)
router.patch('/updatefn', updateFirstname)
router.patch('/updateln', updateLastname)
router.patch('/updateemail', updateValidation, updateEmail)
router.patch('/updatepassword', changePassword)
router.patch('/updateactivity', updateActivity)
router.patch('/updateprofile', updateProfile)
router.patch('/updatesubacc', updateSubAccCode)
router.patch('/updatetotal', updateTotal)
router.put('/updateaccinfo', updateAccountInfo)
router.get('/generate-referral-link/:user_name', getRefLink)
router.get('/getpost/:postId', getPostById)
router.get('/getref-id', getRefId)
router.get('/getref/', getRef)
router.get('/getrefhistory/:id', getHistory)
router.get('/gettopref', getTopReferrals)
router.get('/getreferrals/:userId', getReferrals)
router.get('/getreferralssize/:userId', getReferralsSize) 
 
 
module.exports = router
