const {Router} = require('express')
const { getUsers } = require('../controllers/auth')
const { registerValidation, loginValidation, updateValidation } = require('../vaildators/auth')
const { validationMiddleware } = require('../middlewares/validations-middleware')
const { register } = require('../controllers/register')
const { login } = require('../controllers/login')
const { protected } = require('../controllers/protected')
const { userAuth } = require('../middlewares/auth-middleware')
const { logout } = require('../controllers/logout')
const { updateFirstname, updateLastname, 
    updateEmail, updateAccountInfo, changePassword, 
    updateActivity, updateProfile, updateSubAccCode, updateTotal } = require('../controllers/update')
const { getRefLink, getRefId, getReferrals, getReferralsSize, getTopReferrals } = require('../controllers/referral')
const { getRef, createSub, getHistory } = require('../controllers/paystack')
const { createSponPost, getAllPosts, getPostById } = require('../controllers/sponosredpost')
const { createComment, getCommentForPost } = require('../controllers/comments')
const { getUser } = require('../controllers/getUser')
const { validateData } = require('../controllers/validateRegInfo')
// const { sendImgToCloud } = require('../controllers/cloudinary')
const router = Router()

router.get('/get-users', getUsers) 
router.get('/getuser/:user_id', userAuth, getUser)
router.get('/protected', userAuth, protected)
router.post('/validate-registration', registerValidation, validateData)
router.post('/register', register)
router.post('/login', loginValidation, validationMiddleware, login)
router.post('/createsubaccount', userAuth, createSub) 
router.post('/createapost', userAuth, createSponPost) 
router.post('/posts/:postId/comments', userAuth, createComment) 
router.get('/getallposts', userAuth, getAllPosts) 
router.get('/posts/:postId/comments', userAuth, getCommentForPost) 
router.get('/logout', userAuth, logout)
router.patch('/updatefn', userAuth, updateFirstname)
router.patch('/updateln', userAuth, updateLastname)
router.patch('/updateemail', userAuth, updateValidation, updateEmail)
router.patch('/updatepassword', userAuth, changePassword)
router.patch('/updateactivity', userAuth, updateActivity)
router.patch('/updateprofile',userAuth, updateProfile)
router.patch('/updatesubacc', userAuth, updateSubAccCode)
router.patch('/updatetotal', userAuth, updateTotal)
router.put('/updateaccinfo', userAuth, updateAccountInfo)
router.get('/generate-referral-link/:user_name', userAuth, getRefLink)
router.get('/getpost/:postId', userAuth, getPostById)
router.get('/getref-id', getRefId)
router.get('/getref/', getRef)
router.get('/getrefhistory/:id', getHistory)
router.get('/gettopref', getTopReferrals)
router.get('/getreferrals/:userId',userAuth, getReferrals)
router.get('/getreferralssize/:userId', userAuth, getReferralsSize) 
 
 
module.exports = router
